steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/wink-konnector-dev', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/wink-konnector-dev']
  # Deploy container image to Cloud Run
#- name: 'gcr.io/cloud-builders/gcloud'
#  args: ['beta', 'run', 'deploy', 'wink-konnector-dev', '--image', 'gcr.io/$PROJECT_ID/wink-konnector-dev', '--region', 'us-central1','--platform', 'managed']
images:
- gcr.io/$PROJECT_ID/wink-konnector-dev
